apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullstack-container.fullname" . }}-config
data: 
    config.yaml: |
      bind-addr: 0.0.0.0:1080
      auth: password
      password: {{ .Values.password }}
      cert: false