apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullstack-container.fullname" . }}
  labels:
    {{- include "fullstack-container.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fullstack-container.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fullstack-container.selectorLabels" . | nindent 8 }}
    spec:
      hostname: fullstack
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fullstack-container.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
      initContainers:
        - name: change-coder-data-ownership
          image: alpine
          command: ["/bin/sh","-c"]
          args: ["mkdir -p /code-server/data/config && cp /config.yaml /code-server/data/config/config.yaml && mkdir -p /code-server/data/User && cp /settings.json /code-server/data/User/ && chown 1000:1000 /code-server/data"]
          volumeMounts:
          - name: pvc
            mountPath: "/code-server"
          - name: config-volume
            mountPath: /config.yaml
            subPath: config.yaml
          - name: settings-volume
            mountPath: /settings.json
            subPath: settings.json
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/sh","-c"]
          args: [
              "{{- if .Values.extensions }}
              code-server 
              {{ include "fullstack-container.addExtensions" .  }} 
              --user-data-dir /code-server/data 
              --config /code-server/data/config/config.yaml  
              /code-server/data && 
              {{- end }}
              code-server --user-data-dir /code-server/data
              --config /code-server/data/config/config.yaml  
              /code-server/data" 
              ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DOCKER_HOST 
              value: tcp://localhost:2375 
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          volumeMounts:
          - name: pvc
            mountPath: "/code-server"
          - name: certs-client
            mountPath: /certs/client
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: docker-daemon
          image: "{{ .Values.dockerDaemon.image.repository }}:{{ .Values.dockerDaemon.image.tag }}"
          securityContext:
            {{- toYaml .Values.dockerDaemon.securityContext | nindent 12 }}
          volumeMounts:
          - name: certs-ca
            mountPath: /certs/ca
          - name: certs-ca
            mountPath: /certs/client
          - name: docker-graph-storage
            mountPath: /var/lib/docker
          - name: pvc
            mountPath: "/code-server"
      volumes:
        - name: certs-ca
          emptyDir: {}
        - name: certs-client
          emptyDir: {}
        - name: docker-graph-storage 
          emptyDir: {}
        - name: pvc
          persistentVolumeClaim:
            claimName: {{ include "fullstack-container.fullname" . }}
        - name: config-volume
          configMap:
            name: {{ include "fullstack-container.fullname" . }}-config
        - name: settings-volume
          configMap:
            name: {{ include "fullstack-container.fullname" . }}-settings
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
