apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullstack-container.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 10Gi